config/routes.rb
AppForum::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'topics/tag/:tag', to: 'topics#index', as: :tag

  resources :forums do
    resources :topics
  end
  
  resources :topics do
    resources :comments
  end

  root 'forums#index'  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body, message: "Comment body can't be blank"

  belongs_to :topic
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	validates_presence_of :name, message: "Forum name can't be blank"

	has_many :topics

	acts_as_taggable

  def to_param
    "#{id} #{name}".parameterize
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	validates_presence_of :title, message: "Title can't be blank"

  belongs_to :forum
  has_many :comments

  acts_as_taggable

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  # Comments /comments
  def create
    begin
      @topic = Topic.find(params[:topic_id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    @comment = @topic.comments.create(comment_params)
    respond_to do |format|
      format.html { redirect_to topic_path(@topic) }
      format.js
    end
  end

  # DELETE /comments/1
  def destroy
    begin
      @topic = Topic.find(params[:topic_id])
      @comment = @topic.comments.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end
    
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to topic_path(@topic) }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :topic_id)
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
	
  # GET /forums
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html
    end
  end

  # GET /forums/1
  def show
    begin
      @forum = Forum.where(id: params[:id]).includes(:topics)
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    respond_to do |format|
      format.html
    end
  end

  # GET /forums/new
  def new
    @forum = Forum.new
    respond_to do |format|
      format.html
    end
  end

  # GET /forums/1/edit
  def edit
    begin
      @forum = Forum.find(params[:id])  
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end
  end

  # forum /forums
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /forums/1
  def update
    begin
      @forum = Forum.find(params[:id])  
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    respond_to do |format|
      if @forum.update_attributes(forum_params)
        format.html { redirect_to @forum, notice: 'forum was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /forums/1
  def destroy
    begin
      @forum = Forum.find(params[:id])  
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.js
    end
  end

  private

  def forum_params
    params.require(:forum).permit(:name)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	
  # GET /topics
  def index
    if params[:tag]
      @topics = Topic.tagged_with(params[:tag])
    else
      @topics = Topic.all
    end

    respond_to do |format|
      format.html
    end
  end

  # GET /topics/1
  def show
    begin
      @topic = Topic.where(id: params[:id]).includes(:comments)
      @forum = @topic.first.forum
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    respond_to do |format|
      format.html
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # Topic /topics
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /topics/1
  def update
    begin
      @topic = Topic.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end

    respond_to do |format|
      if @topic.update_attributes(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /topics/1
  def destroy
    begin
      @topic = Topic.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.warn { "Not found" }
      nil
    end
    
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.js
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :forum_id, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>">
<%= comment.body %> <%= link_to 'Destroy', [@topic, comment], method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
</li>

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<ul id="comments">
<% if !@topic.first.comments.blank? %>
    <% @topic.first.comments.each do |a| %>
      <li id="comment_<%= a.id %>">
        <%= a.body %> 
        <%= link_to 'Destroy', [@topic.first, a], method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
      </li>
    <% end %>
  
<% else %>
  <h3 class='no_comments'>No Comments...</h3>
<% end %>
</ul>

app/views/comments/_form.html.erb
<h3>Create Comment </h3>
<%= simple_form_for([@topic.first, @topic.first.comments.build], :remote=> true) do |f| %>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%= j render(@comment) %>');
$('.no_comments').remove();
$('input#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/forums/edit.html.erb
<p>
  <%= form_for @forum do |f| %>

  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited
        this forum from being saved:</h2>
      <ul>
        <% @forum.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</p>

<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<h1>Forums</h1>

<table>
<% @forums.each do |forum| %>
  <tr>
    <td><%= link_to forum.name, forum_path(forum) %> </td>
    <td><%= link_to 'Edit', edit_forum_path(forum) %> </td>
    <td><%= link_to "Delete", forum_path(forum), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<p>
	<%= link_to 'New forum', new_forum_path %>
</p>

app/views/forums/new.html.erb
<p>
  <%= form_for :forum, url: forums_path do |f| %>

  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited
        this forum from being saved:</h2>
      <ul>
        <% @forum.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>
</p>

<%= link_to 'Back', forums_path %>

app/views/forums/show.html.erb
<p>
  <b>Forum name: <%= @forum.first.name %></b>
</p>

<% if !@forum.first.topics.blank? %>
<h2> Topics: </h2>
  <table>
    <% @forum.first.topics.each do |a| %>
      <tr id="topic_<%= a.id %>">
        <td><%= link_to a.title, forum_topic_path(@forum.first, a) %></td>
        <td><%= link_to 'Edit', edit_forum_topic_path(@forum.first, a) %></td>
        <td><%= link_to 'Destroy', forum_topic_path(@forum.first, a), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h3>No Topics...</h3>
<% end %>

<p>
  <%= link_to 'Add topics', new_forum_topic_path(@forum.first) %> | <%= link_to 'All Forums', forums_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppForum</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<p>
  <%= form_for @topic do |f| %>

    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited
          this user from being saved:</h2>
        <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table>
      <tr>
        <td><%= f.label :title %></td>
        <td><%= f.text_field :title %></td>
      </tr>

      <tr class="field">
        <td><%= f.label :tag_list, "Tags (separated by commas)" %></td>
        <td><%= f.text_field :tag_list %></td>
      </tr>

      <%= f.hidden_field :forum_id, value: params[:forum_id] %>

      <tr>
        <td><%= f.submit %></td>
      </tr>
    </table>

  <% end %>
</p>

<p>
<% if params[:forum_id].present? %>
  <%= link_to 'Back', forum_path(params[:forum_id]) %>
<% else %>
  <%= link_to 'All Forums', forums_path %>
<% end %>
</p>

app/views/topics/index.html.erb
<h1>Topics</h1>
<p>
  <% tag_cloud Topic.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</p>

<ul>
  <% @topics.each do |topic| %>
    <li>
      <%= link_to topic.title, topic_path(topic) %> |
      <%= link_to 'Edit', edit_topic_path(topic) %> |
      <%= link_to "Delete", topic_path(topic), method: :delete, data: { confirm: 'Are you sure?' } %></br>
      Tags: <%= raw topic.tag_list.map { |t| link_to t, "/topics/tag/#{t}" }.join(', ') %>
    </li><br/>
  <% end %>
</table>

<p>
  <%= link_to "All Forums", forums_path %>
</p>

app/views/topics/new.html.erb
<h3> Create Topic </h3>
<%= form_for :topic, url: topics_path do |f| %>

<% if @topic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@topic.errors.count, "error") %> prohibited
      this topic from being saved:</h2>
    <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <table>
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr class="field">
      <td><%= f.label :tag_list, "Tags (separated by commas)" %></td>
      <td><%= f.text_field :tag_list %></td>
    </tr>

    <%= f.hidden_field :forum_id, value: params[:forum_id] %>

    <tr>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end %>

<p>
<% if params[:forum_id].present? %>
  <%= link_to 'Back', forum_path(params[:forum_id]) %>
<% else %>
  <%= link_to 'All Forums', forums_path %>
<% end %>
</p>

app/views/topics/show.html.erb
<p>All Tags:
  <% tag_cloud Topic.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</p>

<h1>Topic</h1>

<p>
  Title: <%= @topic.first.title %>
</p>
<p>Tags: <%= raw @topic.first.tag_list.map { |t| link_to t, "/topics/tag/#{t}" }.join(', ') %></p>  

<%= render 'comments/comments' %>

<%= render 'comments/form' %>

<%= link_to 'Back', forum_path(@forum) %>